In [1]:
import numpy as np 
print(np.pi)

3.141592653589793


In [4]:
import numpy as np 
array = np.array([1,2,3,4,5,6,7],dtype="int8")#signed int uses 7 bits for number and one bit for sign(parity)


In [5]:
array.shape

(7,)

In [6]:
array.dtype

dtype('int8')

In [7]:
array

array([1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [8]:
array.nbytes

7

In [ ]:
type(array)# numpy dimension array

numpy.ndarray

In [ ]:
#arr=np.array([1,2,3,"mariam"],dtype="float32")

ValueError: could not convert string to float: 'mariam'

In [ ]:
arra=np.array([1,2,'3.4'],dtype="float32")#converted the string as it's convertable 

In [12]:
array[0]

np.int8(1)

by default int is int32

In [14]:
arr=np.array([1,3-4j],dtype='complex64')
print(arr[1])

(3-4j)


if we wrote only real numbers and stored them as complex numbers it will be stored as real+0j

In [ ]:
array2=np.array(["youssef","Khaled"],dtype="unicode")
array2.dtype
#data is stored according to biggest element size to avoid data loss

dtype('<U7')

In [17]:
#Type conversion astype
arr2=np.array([1,2,3,4,5],dtype="int32")
arr2.dtype


dtype('int32')

In [18]:
R=arr2.astype("int64")
R.dtype

dtype('int64')

In [20]:
l=[1,2,3,4,5]
arrayl=np.array(l)
arrayl.dtype
arrayl

array([1, 2, 3, 4, 5])

In [21]:
l=range(0,10,2)
arrl=np.array(l)
arrl

array([0, 2, 4, 6, 8])

In [23]:
arr,step_size=np.linspace(0,1,100,endpoint=True,retstep=True)
print(arr)
print(arr.size)
print(step_size)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [28]:
arr3=np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np
arr=np.random.rand(2,3,4)#dimensions  
arr

array([[[0.19034857, 0.0029041 , 0.44940737, 0.8188102 ],
        [0.61745861, 0.1890676 , 0.14086713, 0.21703931],
        [0.78811618, 0.13797143, 0.98060166, 0.86622259]],

       [[0.92105716, 0.99113456, 0.51690042, 0.72032306],
        [0.45550418, 0.25652633, 0.36114405, 0.10701231],
        [0.97292617, 0.499337  , 0.33837455, 0.98916469]]])

In [5]:
import numpy as np
arry=np.random.rand(4,3,5,5)#dimensions  
arry

array([[[[0.87930785, 0.06090432, 0.20712449, 0.60050584, 0.38114674],
         [0.05260149, 0.4191806 , 0.66964866, 0.12380136, 0.32801591],
         [0.54513369, 0.07660882, 0.30795453, 0.41735513, 0.55210251],
         [0.42911579, 0.405941  , 0.56847295, 0.99431023, 0.77801904],
         [0.80553549, 0.45093006, 0.89175127, 0.72006243, 0.00798089]],

        [[0.58742791, 0.50467869, 0.34114318, 0.3425107 , 0.71382147],
         [0.53920374, 0.08677727, 0.00709464, 0.80465531, 0.05522392],
         [0.77720546, 0.68951805, 0.13638418, 0.67826634, 0.87647377],
         [0.30408846, 0.21901284, 0.70969801, 0.44733053, 0.3964913 ],
         [0.59263554, 0.19632779, 0.6073218 , 0.34354219, 0.22514011]],

        [[0.943281  , 0.05432929, 0.91766196, 0.11152048, 0.41485134],
         [0.14460262, 0.52870737, 0.05230528, 0.6663129 , 0.55008942],
         [0.04850834, 0.9421743 , 0.07160189, 0.94916527, 0.07269001],
         [0.89892596, 0.57665136, 0.25729669, 0.51850147, 0.40076578],
  

In [6]:
#NULL matrix 
zeros=np.zeros(3)
zeros

array([0., 0., 0.])

In [ ]:
z2=np.zeros((3,2)) # if more than one element then it has to be at a tuple 
z2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
#zero spy takes the dimensions and data types of any array when we take a zeros array of it 
#example
empty =np.zeros(5)
print(empty)
for i in range (5):
    empty[i]=float(input())
print(empty)

[0. 0. 0. 0. 0.]
[1. 2. 3. 4. 5.]


In [ ]:
z3=np.zeros_like(arr) #spy 
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
S=np.array(["A","B","C"],dtype="U")
S

array(['A', 'B', 'C'], dtype='<U1')

In [19]:
Zeros_S=np.zeros_like(S)
Zeros_S

array(['', '', ''], dtype='<U1')

In [22]:
ones=np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
on=np.ones_like(ones)
print(on)
print(str(ones.dtype))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [ ]:
E=np.empty(8) #garbage value gives any random values from memory 
E

array([0.24038735, 0.77706247, 0.13758799, 0.68465764, 0.12477707,
       0.98158846, 0.52615563, 0.53583525])

In [29]:
#empty like
empt=np.empty_like(arr)
print(arr)
print(arr.dtype)

[[[0.19034857 0.0029041  0.44940737 0.8188102 ]
  [0.61745861 0.1890676  0.14086713 0.21703931]
  [0.78811618 0.13797143 0.98060166 0.86622259]]

 [[0.92105716 0.99113456 0.51690042 0.72032306]
  [0.45550418 0.25652633 0.36114405 0.10701231]
  [0.97292617 0.499337   0.33837455 0.98916469]]]
float64


In [30]:
ar=np.array([1,2,3],dtype='int8')
empty=np.empty_like(ar)
empty

array([-2, -1, -1], dtype=int8)

In [35]:
arra=np.array([[1,2]
               ,[3,4]],dtype='int32')
print(arra)
print(arra.dtype)

[[1 2]
 [3 4]]
int32


In [36]:
full=np.full_like(arra,5)
print(full)
print(full.dtype)

[[5 5]
 [5 5]]
int32


In [ ]:
#repetitive manner
#1 repeat
ay=[[1,2,3]
    ,[3,4,5]]
print(np.repeat(ay,4)) #flaten axis 0

[1 1 1 1 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 5 5 5 5]


In [ ]:
a=[[1,2],[3,5]]
np.repeat(a,8,axis=0) # 0 is row and 1 is column

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5],
       [3, 5]])

In [ ]:
#tile repeats the whole structure not only one element like repeat
np.tile(a,5)

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 5, 3, 5, 3, 5, 3, 5, 3, 5]])

In [ ]:
np.tile(a,(2,2)) #repeats every structure two times 

array([[1, 2, 1, 2],
       [3, 5, 3, 5],
       [1, 2, 1, 2],
       [3, 5, 3, 5]])

In [ ]:
m=np.eye(5,5) #identity
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
n=np.eye(5,5,k=2)   #k moves the main  diagonal
n

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
f=np.identity(5) #defines the number of values of main diagonal and the dimensions are defined by it 
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
#diagonal of any array 
d=np.diag(ay)
d

array([1, 4])

In [ ]:
c=np.diag([1,2,3,4,5,6,7]) #define the diagonal
c

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [ ]:
import numpy as np
array=np.array([[1,2,3],[4,5,6]],dtype='int32')
print(np.info(array))
#class=> which class it's in python classes 
#shape => dimensions
#strides => how many bytes we needed till we go to next row 
#itemsize=bytes
#aligned => goes with alignment of pc
#contigous=> takes the whole block and stores it (column major)  
#fortran takes row by row and stores it row style (row major)
#datapointer => address in memory 
#byteorder=> big endian or little endian 
#byteswap => needed swapping before storing or not like big endian for swapping between LSB and MSB
#type => type of my array


class:  ndarray
shape:  (2, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f6b2fc4b40
byteorder:  little
byteswap:  False
type: int32
None


In [6]:
#arr.shape=>prints the dimensions of array 
print(array.shape)

(2, 3)


In [7]:
#length of an array = number of rows
print(len(array))

2


In [ ]:
print(array.ndim) #@D

2


In [9]:
print(array.size)

6


In [10]:
print(array.itemsize)

4


In [ ]:
print(array.nbytes) #6(size)* bytes =24

24


In [14]:
array4=np.array([[1,2,3,4],
                 [1,7,6,5],
                 [8,11,2,4]])
print(array4.dtype )
print(array4.size)
print(array4.ndim)
print(array4.shape)
print(array4.nbytes)
print(array4.nbytes *8)
print(np.info(array4))

int64
12
2
(3, 4)
96
768
class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1f6b0a03f60
byteorder:  little
byteswap:  False
type: int64
None


In [18]:
import numpy as np
#sampling method 
np.random.seed(65)
np.random.rand(3)

array([0.21864505, 0.03140272, 0.28712528])

In [19]:
rs=np.random.RandomState(52)
rs.rand(15)

array([0.82311034, 0.02611798, 0.21077064, 0.61842177, 0.09828447,
       0.62013131, 0.05389022, 0.96065406, 0.98042937, 0.52112765,
       0.63655334, 0.76475695, 0.76495529, 0.41768558, 0.76880531])

In [25]:
#generate random scaler 
print(np.random.rand()*10)

7.715108316681932


In [26]:
#normal distribution 
print(np.random.randn(3,3))

[[-1.59309501  0.08775184  0.03322694]
 [-1.56950039  0.18107099 -1.07770993]
 [ 2.00836161 -0.20120416 -0.71998442]]


In [27]:
print(np.random.randint(1,10,5,'i8'))

[2 7 6 1 7]


In [2]:
import numpy as np
np.random.seed(65)
print(np.random.random_sample(10))
print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.21864505 0.03140272 0.28712528 0.17264466 0.30337638 0.16295022
 0.69931375 0.77151083 0.51455245 0.23580689]
[0.23003963 0.50571517 0.13418496 0.56146226 0.4820002  0.67966876
 0.73870729 0.16514066 0.10069371 0.92758757]
[0.22027153 0.10020807 0.79305629 0.10742643 0.45574091 0.10711613
 0.53257258 0.44607481 0.17972022 0.98504053]
[0.66322649 0.63012838 0.55027065 0.02993737 0.10579117 0.34980868
 0.05040405 0.55165452 0.80687211 0.3766353 ]


In [5]:
import numpy as np
arr_m=np.random.rand(5,5)
print (arr_m)

[[0.27863559 0.89473843 0.67351481 0.31789432 0.14319062]
 [0.04208975 0.67570173 0.16100456 0.09563275 0.62573299]
 [0.12743415 0.94003255 0.46699462 0.93129528 0.53346029]
 [0.60165001 0.016855   0.59310916 0.75210869 0.39016708]
 [0.62126849 0.35461094 0.24991337 0.18980261 0.46582743]]


In [ ]:
print(arr_m+10) # can do any mathematical operation as it's many arrays not a matrix so we can do operations.

[[10.27863559 10.89473843 10.67351481 10.31789432 10.14319062]
 [10.04208975 10.67570173 10.16100456 10.09563275 10.62573299]
 [10.12743415 10.94003255 10.46699462 10.93129528 10.53346029]
 [10.60165001 10.016855   10.59310916 10.75210869 10.39016708]
 [10.62126849 10.35461094 10.24991337 10.18980261 10.46582743]]


In [7]:
arr_s=np.array([1,2,3])
arr_s

array([1, 2, 3])

In [8]:
np.add(arr_s,[5,4,3])

array([6, 6, 6])

In [10]:
np.add(arr_s,[5,4,3],out=arr_s)


array([11, 10,  9])

In [13]:
np.subtract(arr_s,[20,20,20],out=arr_s)

array([ -9, -10, -11])

In [14]:
np.multiply(arr_s,[-1,-1,-1])

array([ 9, 10, 11])

In [17]:
np.divide(arr_s,[3,2,1])

array([ -3.,  -5., -11.])

In [ ]:
arr_n=np.random.rand(5,5)
print(arr_n)
print(arr_n.min())
print(arr_n.max())
print(arr_n.mean())
print(np.median(arr_n))#needs to be passed as a parameter
print(np.var(arr_n))#gets variance 
print(np.std(arr_n))#standard deviation


[[0.69241147 0.81804336 0.90420101 0.59166387 0.29596011]
 [0.34526279 0.96920224 0.26286674 0.77928581 0.03361092]
 [0.15462485 0.26754558 0.70418463 0.45157657 0.51793208]
 [0.57332156 0.86080546 0.59689137 0.6012346  0.52258463]
 [0.40235506 0.34502553 0.47134889 0.01123798 0.03371301]]
0.011237981536530772
0.9692022438307624
0.4882756047554933
0.5179320818450958


In [22]:
arr_f=np.random.rand(6,6)
print(arr_f)
print(arr_f.min())
print(arr_f.max())
print(arr_f.mean())
print(np.median(arr_f))#needs to be passed as a parameter
print(np.var(arr_f))#gets variance 
print(np.std(arr_f))#standard deviation

[[0.25867776 0.44276908 0.3426826  0.14036155 0.21200492 0.12448595]
 [0.93339103 0.40243904 0.55710121 0.08214168 0.37947679 0.76137538]
 [0.1508203  0.55377762 0.34633942 0.97085745 0.52136218 0.99061408]
 [0.48236481 0.86990693 0.2400545  0.42765087 0.77826434 0.23220297]
 [0.74097163 0.91990798 0.43320204 0.40980542 0.04426685 0.16635735]
 [0.21124989 0.13469701 0.04630253 0.89102404 0.35750661 0.08201894]]
0.0442668520445072
0.9906140813578665
0.4344009100094381
0.39095791834462595
0.08471261929851155
0.291054323621058


In [27]:
arr_r=np.random.rand(5,5)
print(arr_r)
print("*****************************")
print(arr_r.min(axis=0)) #axis=0----> row
print("*****************************")
print(arr_r.min(axis=1))


[[0.50639652 0.0087236  0.65389808 0.77265941 0.02056463]
 [0.18648959 0.47128322 0.92945879 0.59737986 0.49664443]
 [0.00732564 0.56401309 0.2735433  0.26852169 0.41895454]
 [0.76270381 0.28771428 0.26923601 0.34335258 0.62045471]
 [0.7653413  0.00570651 0.17653667 0.73094942 0.32782933]]
*****************************
[0.00732564 0.00570651 0.17653667 0.26852169 0.02056463]
*****************************
[0.0087236  0.18648959 0.00732564 0.26923601 0.00570651]


In [ ]:
print(np.argmin(arr_r)) #gets the index of the minimum number 
print(np.argmax(arr_r))#gets the index of the maximum number 
print(np.argmin(arr_r, axis=0)) #for each row the index of minimum in each row 
print(np.argmin(arr_r,axis=1)) #for each column the index of minimum in each column

21
7
[2 4 4 2 0]
[1 0 0 2 1]


In [ ]:
arr_e=np.array([1,2,3])
print(np.exp(arr_e)) #exponential e
print(np.exp2(arr_e)) #2 power each element

[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]


In [35]:
print(np.sqrt(arr_e))

[1.         1.41421356 1.73205081]


In [36]:
print(np.sum(arr_e))

6


In [ ]:
print(np.log(arr_e))#ln

[0.         0.69314718 1.09861229]


In [38]:
print(np.log10(arr_e))

[0.         0.30103    0.47712125]


In [ ]:
print(np.log1p(arr_e))#sum one before getting the log to know if there is a zero (for outliers)

[0.69314718 1.09861229 1.38629436]


In [ ]:
print(np.log2(arr_e))

[0.        1.        1.5849625]


In [41]:
arr_A=np.array([0,1,2])
print(np.log2(arr_A))

[-inf   0.   1.]


C:\Users\maria\AppData\Local\Temp\ipykernel_25672\2954999465.py:2: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(arr_A))


In [44]:
arr1=np.array([1,2,3,4,5,6,7])
arr2=np.array([7,5,2,17,1,0,7])
arr1==arr2

array([False, False, False, False, False, False,  True])

In [45]:
arr1>arr2

array([False, False,  True, False,  True,  True, False])

In [46]:
arr1<arr2

array([ True,  True, False,  True, False, False, False])

In [47]:
arr1>10

array([False, False, False, False, False, False, False])

In [48]:
arr2>10

array([False, False, False,  True, False, False, False])

In [49]:
arr_t=np.array([[1,2,3],
                [4,5,6],])
print(arr_t.T)

[[1 4]
 [2 5]
 [3 6]]


In [53]:
arr_d=np.array([[1,2],
                [3,6]])
print(np.linalg.det(arr_d))

0.0


In [54]:
arr_d2=np.array([[1,2],
                [5,6]])
print(np.linalg.det(arr_d2))

-3.999999999999999
